# Generated by Django 3.1.4 on 2020-12-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Node',
            new_name='Note',
        ),
    ]
