# Generated by Django 3.1.4 on 2020-12-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20201213_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='archive'),
        ),
    ]
