# Generated by Django 3.1.4 on 2020-12-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20201201_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='archive',
            field=models.BooleanField(blank=True, null=True, verbose_name='archive'),
        ),
    ]
