# Generated by Django 3.1.4 on 2020-12-28 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.list
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('note', '0009_note_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteListView',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(django.views.generic.list.ListView, 'taggit.tag'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
    ]
