# Generated by Django 3.1.4 on 2020-12-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('note', '0010_auto_20201228_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteListView',
        ),
    ]
