# Generated by Django 3.1.4 on 2020-12-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0011_delete_notelistview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated'),
        ),
    ]
