# Generated by Django 3.1.4 on 2020-12-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0014_auto_20201229_1208'),
        ('note', '0012_auto_20201229_1134'),
    ]

    operations = [
    ]
