# Generated by Django 3.1.4 on 2020-12-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0015_merge_20201229_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('icon', models.ImageField(blank=True, upload_to='images', verbose_name='image')),
                ('note', models.ManyToManyField(related_name='notatka', to='note.Note')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
